### ISSUE TITLE
The app should detect if h1z1.exe is in the same folder

### ISSUE THREAD

**Issue by QuentinGruber** [H1emu/H1emu-server-app#23]

**Comment by Noctiamor** [comment]
For this you can do something as simple as:

`if (File.Exists("h1z1.exe"))
            {
                MessageBox.Show("Nice");
            }
            else
            {
                MessageBox.Show("Put H1Emu app inside of H1Z1 directory.");
            }`

On maybe the form load event.

**Comment by QuentinGruber** [comment]
oh thx @Eavileswayce i will add that 😎
